#!/usr/bin/env bash

CONFIG_FILE="$HOME/.config/wallpapers/theme.conf"

THEME=""
if [ -f $CONFIG_FILE ]; then
	THEME=$(cat $CONFIG_FILE)
fi

WALLPAPER_DIR="$WALLPAPER_DIR/$THEME"
CURRENT_WALL=$(hyprctl hyprpaper listloaded):

# Get a random wallpaper that is not the current one
WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

# Apply the selected wallpaper
hyprctl hyprpaper wallpaper ,"$WALLPAPER"
