#!/usr/bin/env bash

CONFIG_DIR="$HOME/.local/share/wallpapers"
CONFIG_FILE=$CONFIG_DIR/theme.conf

if [ ! -d $CONFIG_DIR ]; then
	mkdir $CONFIG_DIR
else
	if [ -f $CONFIG_FILE ]; then
		current_theme="$(cat $CONFIG_FILE)"
	fi
fi

if [ -z $current_theme ]; then
	current_theme="all"
fi

THEMES=$(find "$WALLPAPER_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)
THEMES="all
$THEMES"

new_theme=$(echo "$THEMES" | wofi -d -p "current theme : '$current_theme'")

if [ -z $new_theme ]; then
	exit
fi

if [ $new_theme = "all" ]; then
	new_theme=""
fi

echo $new_theme > $CONFIG_FILE

set-random-wallpaper
