#!/usr/bin/env bash

CONFIG_DIR="$HOME/.local/share/wallpapers"
CONFIG_FILE=$CONFIG_DIR/theme.conf

if [ ! -d $CONFIG_DIR ]; then
	mkdir $CONFIG_DIR
fi

THEMES="$(find "$WALLPAPER_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)"

echo "$THEMES" | wofi -d -O=alphabetical -p "Pick a theme (escape for all)" > $CONFIG_FILE

set-random-wallpaper
