#!/usr/bin/env bash

yay -S --noconfirm --needed keepassxc nextcloud-client firefox
yay -S --noconfirm --needed brave-bin stremio tidal-hifi obsidian discord

# As of July 2025 vlc has split out some of the plugins from the main package?
# In any case, if you find you run into codec issues, try installing the vlc-plugins-all package, that seems to resolve it.
yay -S --noconfirm --needed vlc vlc-plugins-all


# terminal audio visualiser
yay -S --noconfirm --needed cava

# Music Streaming Service
# yay -S --noconfirm --needed tidal-hifi
yay -S --noconfirm --needed spotify-launcher
