#!/usr/bin/env bash

yay -S --noconfirm --needed git
yay -S --noconfirm --needed ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols

echo "Setting global git user details"
git config --global user.email "dev@jsapsed.co.uk"
git config --global user.name "Jeremy Sapsed"

