#!/usr/bin/env bash

yay -S --noconfirm --needed btop ghostty pwvucontrol rose-pine-hyprcursor unzip ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols ttf-font-awesome samba

# allows you to send desktop notifications via dunst from the cli
yay -S --noconfirm --needed libnotify


