#!/usr/bin/env bash

yay -S --noconfirm --needed btop pwvucontrol waybar hyprpicker hyprpaper hyprlock unzip

# allows you to send desktop notifications via dunst from the cli
yay -S --noconfirm --needed libnotify


