#!/usr/bin/env bash

CRED_DIR=$XDG_DATA_HOME/nas
CRED_FILE=$CRED_DIR/smb-credentials

if [ ! -d $CRED_DIR ]; then
	echo "Creating directory $CRED_DIR"
	mkdir $CRED_DIR
fi

echo "Samba username:"
read username

echo "Samba password:"
read password

echo "username=$username
password=$password
domain=WORKGROUP" > $CRED_FILE

echo "Credientials saved to $CRED_FILE"
chmod 600 $CRED_FILE
