#!/usr/bin/env bash

yay -S --noconfirm --needed gcc make git ripgrep fd unzip neovim
#
# TODO: Update this to use my own config repos
git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
