#!/usr/bin/env bash

yay -S --noconfirm --needed openssh

KEYFILE=$HOME/.ssh/id_ed25519

if [ -f $KEYFILE ]; then
	echo "SSH keys already generated at $KEYFILE"
else
	ssh-keygen -t ed25519 -f $KEYFILE -N ''
fi
